version: 1.0.{build}
image: Visual Studio 2017

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: '\HG-TradfriInterface\Output\HG-TradfriInterface.zip'

deploy:
  release: V$(appveyor_build_version)
  description: 'IkeaTradfiInterface Version $(appveyor_build_version)'
  provider: GitHub
    auth_token:
    secure: 6xpJrNRZ7YlU22YNrDRs9dAmvp2LIJ4O7t+a5443/NERIk9Aspip7glMn9O4sqU6
  draft: false
  prerelease: true
  on:
    branch: master                  # release from master branch only
 #   appveyor_repo_tag: false        # deploy on tag push only