version: 1.0.{build}
image: Visual Studio 2017

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: '\HG-TradfriInterface\Output\HG-TradfriInterface.zip'

deploy:
  release: V$(appveyor_build_version)
  description: 'IkeaTradfiInterface Version $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: nNJ0tuvMX88/5GPQFV4mtqQe3pRgsJlOd8pvbi0+WeCOsyeNY3L///lRC8pF29wo6J+5b6TPLDDKdKGXveZo9FICP+6k95LkQCvlFzaXb4I=
  draft: false
  prerelease: true
  on:
    branch: master                  # release from master branch only
 #   appveyor_repo_tag: false        # deploy on tag push only